-- 코드를 입력하세요
SELECT A.PRODUCT_ID,
B.PRODUCT_NAME,
SUM(A.AMOUNT) * B.PRICE AS TOTAL_SALES
FROM FOOD_ORDER A
INNER JOIN FOOD_PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE TO_CHAR(A.PRODUCE_DATE,'YYYY-MM') = '2022-05'
GROUP BY A.PRODUCT_ID, B.PRODUCT_NAME, B.PRICE
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC

